package com.example.researchgate.enums;

import lombok.Getter;

@Getter
public enum CodeEnum {
    OK(200, "success"),
    SERVER_ERROR(-1,"网络错误请重试"),
    LOGIN_NEED(1, "请登录"),
    PARAM_ILLEGAL(2, "参数错误"),
    DATA_NOT_EXISTS(3,"数据不存在"),
    DEVICE_UNBIND(4, "设备未绑定"),
    RECORD_STATUS_ILLEGAL(5, "结佣单非人工审核状态"),
    USERID_REBIND(6, "用户已关联该人脸，关联失败"),
    RECORD_STATUS_NOT_NOPAY(7, "结佣单非不予结佣状态"),
    RULE_ADVANCE_REPORT_TIME_ILLEGAL(8, "规则提前报备时间填写错误"),
    RULE_VALID_ARRIVE_TIME_ILLEGAL(9, "规则到访有效期填写错误"),
    RULE_VALID_SIGN_TIME_ILLEGAL(10, "规则成交保护有效期填写错误"),
    UPLOAD_FILE_FAIL(11, "上传文件失败"),
    FACE_QUALITY_INVALID(12, "图片质量不合格"),
    CREATE_PERSON_FAIL(13, "创建人员失败"),
    SEARCH_PERSON_FAIL(14, "人员搜索失败"),
    RULE_NAME_EXIST(15, "规则名称与已有规则重复"),
    USERID_ALREADY_BINDED(16, "该人脸已经匹配认证客户，关联失败"),
    RECORD_CUSTOMER_REPEATED(17, "结佣单中存在重复购房人"),
    MATCH_FACE_UNEXIST(18, "未搜索到匹配的人脸"),
    PROGRAM_CODE_ERROR(19, "项目编码有误，请重新输入"),
    REMOTE_VERIFY_CLOSED(20, "无法使用远程核验功能，请您联系工作人员"),
    IMAGE_UPLOAD_FAILED(21, "图片上传失败"),
    VERIFY_COMPARE_FAILED(22, "人脸与证件照片不符，请重新拍摄"),
    VERIFY_CODE_UNCHANGED(23, "远程认证处于关闭状态，无法修改项目编码"),
    VERIFY_CARD_INFO_ERROR(24, "证件信息有误，请重新上传"),
    VERIFY_NO_CARD_DETECT(25, "未检测到证件，请重新上传"),
    VERIFY_OCR_FAILED(26, "识别失败，请重新上传"),
    VERIFY_OCR_OTHER_ERROR(27, "系统异常，请重试"),
    VERIFY_GET_CARD_IMAGE_FAILED(28, "系统异常，请重试"),
    VERIFY_OCR_IMAGE_NO_TEXT(29, "未检测到证件，请重新上传"),
    FILE_ILLEGAL(30,"模板有误请重新下载"),
    FACE_UNDETECTED(31, "未检测到人脸，请重新拍摄"),
    FACE_QUALITY_UNSATISFIED(32, "图像质量不符合要求，请重新拍摄"),
    OCR_NAME_NULL(33, "姓名不能为空，请重新填写"),
    OCR_NAME_TOO_LONG(34, "姓名字符数不能超过40，请重新填写"),
    OCR_SEX_TYPE_ERROR(35, "请填写正确的性别信息"),
    OCR_CARD_ID_NUM_NULL(36, "身份证号不能为空，请重新填写"),
    OCR_CARD_ID_NUM_ERROR(37, "请填写正确的18位身份证号"),
    VERIFY_CODE_NUM_ERROR(38, "请填写正确的6位项目编码"),
    CARD_ALREADY_EXIST(40, "该身份证号已经认证，请勿重复认证"),
    OCR_YEAR_ILLEGAL(41, "不符合年龄要求，请您联系工作人员"),
    OCR_VALID_DATE(42, "身份证有效期不合法"),
    OCR_EDGE_INCOMPLETE(43, "身份证边框不完整"),
    OCR_INFO_ERROR(44, "证件信息有误"),
    OCR_INNER_EDGE_INCOMPLETE(45, "身份证框内遮挡"),
    DETECT_LIVE_FACE_ERROR(46, "人脸照片不符合要求，请重新拍摄"),
    USER_NOT_EXIST(47, "该用户不存在"),
    COMMISSION_SET_ERRROR(48, "平均佣金金额设置错误"),
    RECORD_ADD_CUSTOMER_NAME_ERROR(49, "客户姓名与身份证姓名不同"),
    CUSTOMER_CARD_NO_ERROR(50, "客户证件号格式不正确"),
    TEMPLATE_IS_BLANK(51, "模板未填写"),
    REGISTER_QR_CODE_ERROR(52, "顾问签到扫码失败"),
    CUSTOMER_VISI_CONFIRMED(53, "客户没有处于待确客状态"),
    CUSTOMER_VISI_CONFIRMED_OTHER(54, "客户已通过其他方式确认机构归属"),
    BROKER_ON_SERVICE(55, "系统分配顾问有变化，请重新提交"),
    WECHAT_ERROR(56, "微信接口请求失败"),
    NO_BROKER_ON_SERVICE(57, "当前无可分配顾问"),
    BROKER_REST(58, "当前顾问休息中，无法接待"),
    CUSTOMER_BINDED_RECORD(59, "当前客户已建立结佣单，无法删除"),
    ACCOUNT_NOT_EXIST(210, "当前案场未开通识客宝"),
    FILE_WRONG(60,"模板有误！请确认导入文件与所选模板保持一致"),
    Point_NULL(61,"还有没有输入的点位参数"),
    Point_Len_Error(62,"距离类参数应为范围为0-30m的整数或小数"),
    IMAGE_CAPTCHA_INVALID(600, "验证失败，请重试"),
    SMS_CAPTCHA_FAIL(601, "获取手机验证码失败(%s)"),
    SMS_CAPTCHA_INVALID(602, "请输入正确的验证码"),
    SMS_CAPTCHA_LOCK(603, "验证码连续错误%s次，请%s分钟后再尝试登录"),
    USER_NO_PERMISSION(604, "该手机号未开通登录权限"),
    LOGIN_REQUIRED(605, "未登录"),
    LOGIN_EXPIRED(606, "登录状态已过期，请重新登录"),
    WECHAT_LOGIN_ERROR(607, "微信登录失败(%s)"),
    UPLOAD_FAIL(608, "上传失败"),
    SECURITY_CHECK_WARN(609, "检测到敏感信息，操作失败"),
    DEPENDENT_SERVICE_ERROR(502, "中间服务异常"),
    ADD_USER_FAIL(610, "注册失败"),
    LOGIN_MISS_CONTENT(611,"没有输入用户必要userId或者UserEmail"),
    PASSWORD_WRONG(612,"用户名或者密码错误"),
    GET_NOTICE_FAIL(613,"获取通知失败"),
    EDIT_INTRODUCTION_FAIL(614,"更新用户简介失败"),
    SEND_MESSAGE_FAIL(615,"发送信息失败"),
    GET_DIALOG_FAIL(616,"获取对话失败"),
    GET_MSG_GROUP_FAIL(617,"查询用户参与的消息组失败"),
    GET_USER_FAIL(618,"获取用户信息失败"),
    GET_USER_LIST_FAIL(619,"获取重名用户列表失败"),
    ADD_QUESTION_FAIL(620,"添加问题失败"),
    DEL_QUESTION_FAIL(621,"删除问题失败"),
    GET_QUESTION_FAIL(622,"获取问题失败"),
    SEARCH_QUESTION_FAIL(623,"搜索问题失败"),
    ADD_ANSWER_FAIL(624,"添加问题失败"),
    USER_FOLLOW_FAIL(625,"关注失败"),
    UN_USER_FOLLOW_FAIL(626,"取消关注失败"),
    GET_FOLLOW_LIST_FAIL(627,"获取关注列表失败"),
    GET_GRAPH_FAIL(628,"获取用户图谱失败"),
    ;

    private int code;
    private String msg;

    CodeEnum(int code, String msg) {
        this.code = code;
        this.msg = msg;
    }
}
