spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true
  datasource:
    url: jdbc:mysql://43.140.248.122:3306/crc?serverTimezone=GMT%2b8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  session:
    store-type: none
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.researchgate.Entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8090



#logging:
#  config: classpath:log/log4j2.xml

